### ISSUE TITLE
Readme seems outdated

### ISSUE THREAD

**Issue by Franco-Alejandro** [webalys-hq/streamline-wrapper-angular#1] opened 2020-12-18 12:10 UTC
Hello, the readme seems outdated. Tried to implement the wrapper but I had to follow the demo that's inside the project which first defines an `Icon ` rather than importing the icon itself on ts

**Comment by cbrwizard** [comment] 2020-12-25 22:09
Closing as duplicate of https://github.com/webalys-hq/streamline-wrapper-angular/issues/2

**Closed by cbrwizard** 2020-12-25 22:09 UTC
